# Generated by Django 5.2.4 on 2025-07-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_content_count', models.IntegerField(default=0)),
                ('total_content_count', models.IntegerField(default=0)),
                ('content_by_grade', models.JSONField(default=dict)),
                ('content_by_topic', models.JSONField(default=dict)),
                ('total_questions_answered', models.IntegerField(default=0)),
                ('questions_by_type', models.JSONField(default=dict)),
                ('average_response_time', models.FloatField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('topics_covered', models.IntegerField(default=0)),
                ('most_active_persona', models.CharField(blank=True, max_length=50)),
                ('persona_usage_stats', models.JSONField(default=dict)),
                ('content_upload_trend', models.JSONField(default=list)),
                ('question_trend', models.JSONField(default=list)),
                ('rating_trend', models.JSONField(default=list)),
                ('avg_retrieval_time', models.FloatField(default=0)),
                ('avg_llm_response_time', models.FloatField(default=0)),
                ('total_tokens_used', models.BigIntegerField(default=0)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_metrics',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('general', 'General Feedback'), ('content', 'Content Suggestion')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('query_type', models.CharField(choices=[('question', 'Question Answering'), ('nl_to_sql', 'Natural Language to SQL'), ('content_search', 'Content Search'), ('persona_chat', 'Persona Chat')], max_length=20)),
                ('response', models.JSONField()),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'query_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query_type'], name='query_logs_query_t_6e46ba_idx'), models.Index(fields=['created_at'], name='query_logs_created_480d84_idx'), models.Index(fields=['session_id'], name='query_logs_session_4ff22b_idx')],
            },
        ),
    ]
