# Generated by Django 5.2.4 on 2025-07-12 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_tutor', '0001_initial'),
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRetrievalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('rank', models.PositiveIntegerField()),
                ('was_helpful', models.BooleanField(blank=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrievals', to='knowledge_base.content')),
                ('question_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrievals', to='ai_tutor.questionanswer')),
            ],
            options={
                'db_table': 'content_retrieval_logs',
                'indexes': [models.Index(fields=['question_answer', 'rank'], name='content_ret_questio_987d2f_idx'), models.Index(fields=['content', 'similarity_score'], name='content_ret_content_4949d1_idx')],
                'unique_together': {('question_answer', 'content')},
            },
        ),
        migrations.CreateModel(
            name='NLToSQLQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natural_language_query', models.TextField()),
                ('generated_sql', models.TextField()),
                ('execution_result', models.JSONField()),
                ('execution_success', models.BooleanField()),
                ('error_message', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_tutor.questionanswer')),
            ],
            options={
                'verbose_name': 'Natural Language to SQL Query',
                'verbose_name_plural': 'Natural Language to SQL Queries',
                'db_table': 'nl_to_sql_queries',
                'indexes': [models.Index(fields=['execution_success'], name='nl_to_sql_q_executi_d0901a_idx'), models.Index(fields=['created_at'], name='nl_to_sql_q_created_6e8f69_idx')],
            },
        ),
    ]
